// Pure parsing / formatting helpers used by the scheduler. Extracted so
// they can be unit-tested without spinning up the class and to keep the
// state-machine file focused on control flow.

import type { BatchConflict } from "./types";

/**
 * Parser for the reviewer verdict. The system prompt (`review.md`) asks
 * the agent to return `VERDICT: approved | retry` on the first line. We
 * tolerate uppercase and dashes — and if we don't find the header, we
 * assume `retry` with the full text as notes (better a false retry than
 * a false approved).
 */
export function parseReviewVerdict(text: string): { approved: boolean; notes: string } {
  const lines = text.split(/\r?\n/);
  for (const line of lines) {
    const m = line.match(/^\s*(?:VERDICT|VEREDICTO)\s*[:=]\s*([\w-]+)/i);
    if (m) {
      const v = m[1].toLowerCase();
      const approved = v === "approved" || v === "aprobado" || v === "ok";
      // Notes: everything that comes after the header.
      const idx = text.indexOf(line);
      const notes = text.slice(idx + line.length).trim();
      return { approved, notes: approved ? "" : notes };
    }
  }
  return { approved: false, notes: text.trim() };
}

/**
 * Combines the "before" and "after" snapshots into a single legible blob.
 * To keep the .diff file useful without making it unmanageable, we store
 * the "after" diff (which already includes the agent's changes relative
 * to HEAD) and a header with the date. The "before" is preserved as a
 * leading comment for auditing — if the user sees an agent overwriting
 * prior work, it will show up there.
 */
export function buildAgentDiff(diffBefore: string, diffAfter: string): string {
  const stamp = new Date().toISOString();
  const parts: string[] = [];
  parts.push(`# Snapshot diff generated by the loop scheduler · ${stamp}`);
  parts.push("# (reflects the delta relative to HEAD after the agent run)");
  if (diffBefore.trim() && diffBefore.trim() !== diffAfter.trim()) {
    parts.push("#");
    parts.push("# --- prior state (summary) ---");
    for (const line of diffBefore.split(/\r?\n/).slice(0, 40)) {
      parts.push(`# ${line}`);
    }
    parts.push("# --- post-agent state ---");
  }
  parts.push("");
  parts.push(diffAfter.trim() || "(no changes relative to HEAD)");
  parts.push("");
  return parts.join("\n");
}

/**
 * Section 8.4 · structural conflict detection between phases of the same
 * batch. Parses the `diff --git a/<path> b/<path>` headers (canonical git
 * diff format). If two or more phases touch the same path, we report it.
 *
 * Not bulletproof — an agent could have written a file via shell without
 * git registering it (new untracked), but our snapshot includes untracked
 * as `# - <path>` lines on the side (see `git_diff_sync` in Rust). We
 * consume those too.
 *
 * Returns an ordered list of `{ path, phases[] }` with conflicting paths.
 */
export function detectBatchConflicts(
  diffs: Array<{ phaseSlug: string; phaseName: string; diff: string }>,
): BatchConflict[] {
  const pathToPhases = new Map<string, Set<string>>();
  const headerRe = /^diff --git a\/(.+?) b\/(.+?)$/gm;
  const untrackedRe = /^# - (.+)$/gm;

  for (const { phaseSlug, diff } of diffs) {
    if (!diff) continue;
    const seen = new Set<string>();
    let m: RegExpExecArray | null;
    headerRe.lastIndex = 0;
    while ((m = headerRe.exec(diff)) !== null) {
      // a/b refer to the same path on in-place changes; renames use a!=b.
      // We report both sides so a rename gets flagged against any phase
      // that touches either the original or the new path.
      const a = m[1].trim();
      const b = m[2].trim();
      if (a) seen.add(a);
      if (b && b !== a) seen.add(b);
    }
    untrackedRe.lastIndex = 0;
    while ((m = untrackedRe.exec(diff)) !== null) {
      const p = m[1].trim();
      if (p) seen.add(p);
    }
    for (const path of seen) {
      let set = pathToPhases.get(path);
      if (!set) {
        set = new Set<string>();
        pathToPhases.set(path, set);
      }
      set.add(phaseSlug);
    }
  }

  const conflicts: BatchConflict[] = [];
  for (const [path, phases] of pathToPhases) {
    if (phases.size >= 2) {
      conflicts.push({ path, phases: Array.from(phases).sort() });
    }
  }
  conflicts.sort((a, b) => a.path.localeCompare(b.path));
  return conflicts;
}

/**
 * Section 8.3 · parsing of the integrator verdict. The `integration.md`
 * prompt asks to close with `INTEGRATION: ok` or `INTEGRATION: blocker`.
 * We tolerate uppercase/whitespace. If the header is missing, we assume
 * `ok` to avoid false blocks (the structural detector will still stop us
 * if there's a real conflict).
 */
export function parseIntegrationVerdict(text: string): { status: "ok" | "blocker" } {
  const lines = text.split(/\r?\n/);
  for (let i = lines.length - 1; i >= 0; i--) {
    const m = lines[i].match(/^\s*INTEGRATION\s*[:=]\s*([\w-]+)/i);
    if (m) {
      const v = m[1].toLowerCase();
      if (v === "blocker" || v === "block") return { status: "blocker" };
      return { status: "ok" };
    }
  }
  return { status: "ok" };
}

/**
 * Truncates a long blob for the integrator input. Keeps the first and
 * last N lines + a placeholder in the middle. Prevents a large diff or
 * implementation md from consuming the entire context window.
 */
export function truncateForIntegrator(text: string, maxLines = 200): string {
  const lines = text.split(/\r?\n/);
  if (lines.length <= maxLines) return text;
  const head = lines.slice(0, Math.floor(maxLines / 2));
  const tail = lines.slice(-Math.floor(maxLines / 2));
  return [
    ...head,
    `... (truncated · ${lines.length - maxLines} line(s) omitted) ...`,
    ...tail,
  ].join("\n");
}
