import type { BatchConflict } from "./types";

/**
 * Parses the reviewer verdict header (`VERDICT: approved | retry`). Falls
 * back to `retry` with the full text as notes when the header is missing —
 * better a false retry than a false approval.
 */
export function parseReviewVerdict(text: string): { approved: boolean; notes: string } {
  const lines = text.split(/\r?\n/);
  for (const line of lines) {
    const m = line.match(/^\s*(?:VERDICT|VEREDICTO)\s*[:=]\s*([\w-]+)/i);
    if (m) {
      const v = m[1].toLowerCase();
      const approved = v === "approved" || v === "aprobado" || v === "ok";
      const idx = text.indexOf(line);
      const notes = text.slice(idx + line.length).trim();
      return { approved, notes: approved ? "" : notes };
    }
  }
  return { approved: false, notes: text.trim() };
}

export function buildAgentDiff(diffBefore: string, diffAfter: string): string {
  const stamp = new Date().toISOString();
  const parts: string[] = [];
  parts.push(`# Snapshot diff generated by the loop scheduler · ${stamp}`);
  parts.push("# (reflects the delta relative to HEAD after the agent run)");
  if (diffBefore.trim() && diffBefore.trim() !== diffAfter.trim()) {
    parts.push("#");
    parts.push("# --- prior state (summary) ---");
    for (const line of diffBefore.split(/\r?\n/).slice(0, 40)) {
      parts.push(`# ${line}`);
    }
    parts.push("# --- post-agent state ---");
  }
  parts.push("");
  parts.push(diffAfter.trim() || "(no changes relative to HEAD)");
  parts.push("");
  return parts.join("\n");
}

/**
 * Detects paths touched by more than one phase of the same batch. Parses
 * canonical `diff --git a/<path> b/<path>` headers plus our snapshot's
 * `# - <path>` lines for untracked files (see `git_diff_sync` in Rust).
 */
export function detectBatchConflicts(
  diffs: Array<{ phaseSlug: string; phaseName: string; diff: string }>,
): BatchConflict[] {
  const pathToPhases = new Map<string, Set<string>>();
  const headerRe = /^diff --git a\/(.+?) b\/(.+?)$/gm;
  const untrackedRe = /^# - (.+)$/gm;

  for (const { phaseSlug, diff } of diffs) {
    if (!diff) continue;
    const seen = new Set<string>();
    let m: RegExpExecArray | null;
    headerRe.lastIndex = 0;
    while ((m = headerRe.exec(diff)) !== null) {
      // Renames use a!=b; report both sides so a rename gets flagged
      // against any phase that touches either the original or the new path.
      const a = m[1].trim();
      const b = m[2].trim();
      if (a) seen.add(a);
      if (b && b !== a) seen.add(b);
    }
    untrackedRe.lastIndex = 0;
    while ((m = untrackedRe.exec(diff)) !== null) {
      const p = m[1].trim();
      if (p) seen.add(p);
    }
    for (const path of seen) {
      let set = pathToPhases.get(path);
      if (!set) {
        set = new Set<string>();
        pathToPhases.set(path, set);
      }
      set.add(phaseSlug);
    }
  }

  const conflicts: BatchConflict[] = [];
  for (const [path, phases] of pathToPhases) {
    if (phases.size >= 2) {
      conflicts.push({ path, phases: Array.from(phases).sort() });
    }
  }
  conflicts.sort((a, b) => a.path.localeCompare(b.path));
  return conflicts;
}

/**
 * Parses the integrator verdict (`INTEGRATION: ok | blocker`). Falls back
 * to `ok` when the header is missing — the structural detector will still
 * catch a real conflict.
 */
export function parseIntegrationVerdict(text: string): { status: "ok" | "blocker" } {
  const lines = text.split(/\r?\n/);
  for (let i = lines.length - 1; i >= 0; i--) {
    const m = lines[i].match(/^\s*INTEGRATION\s*[:=]\s*([\w-]+)/i);
    if (m) {
      const v = m[1].toLowerCase();
      if (v === "blocker" || v === "block") return { status: "blocker" };
      return { status: "ok" };
    }
  }
  return { status: "ok" };
}

export function truncateForIntegrator(text: string, maxLines = 200): string {
  const lines = text.split(/\r?\n/);
  if (lines.length <= maxLines) return text;
  const head = lines.slice(0, Math.floor(maxLines / 2));
  const tail = lines.slice(-Math.floor(maxLines / 2));
  return [
    ...head,
    `... (truncated · ${lines.length - maxLines} line(s) omitted) ...`,
    ...tail,
  ].join("\n");
}
